######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 23 11:00:32 2010
######################################################################
TEMPLATE = app
TARGET = server
DEPENDPATH += .
QT += network xml 
CONFIG += console
INCLUDE += ../common
# Input
HEADERS += server.h msg.h
SOURCES += main.cpp server.cpp ../common/msg.cpp
