######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 12 11:09:01 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lqjson


# Input
HEADERS += ../msg.h
SOURCES += main.cpp ../msg.cpp
