######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 23 11:00:32 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . ../common
INCLUDEPATH += . ../common
QT += network xml 
LIBS += -lqjson
CONFIG += console

# Input
HEADERS += client.h msg.h
SOURCES += main.cpp client.cpp  msg.cpp
