######################################################################
# Automatically generated by qmake (2.01a) ?? 11? 16 14:48:24 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += irc.h
SOURCES += irc.cpp main.cpp
