######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 23 11:00:32 2010
######################################################################

TEMPLATE = lib
DEPENDPATH += .
INCLUDEPATH += . 
QT += network xml 
MOC_DIR = ../../tmp
OBJECTS_DIR = ../../tmp
DESTDIR = ../../lib

CONFIG += console

HEADERS += interface.h 
SOURCES += interface.cpp 
