######################################################################
# Automatically generated by qmake (2.01a) ?? 11? 16 14:48:24 2010
######################################################################
TEMPLATE = lib
TARGET = ../../server/plugins
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += irc.h ../../service/protocolinterface.h
SOURCES += irc.cpp
