######################################################################
# Automatically generated by qmake (2.01a) ?? 11? 16 14:48:24 2010
######################################################################
TEMPLATE = lib
TARGET = ../../../lib/irc
DEPENDPATH += .
INCLUDEPATH += .
QT += network
QMAKE_POST_LINK += cp irc.h ../../../include/

# Input
HEADERS += irc.h
SOURCES += irc.cpp
