######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 23 11:00:32 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += network xml 

CONFIG += console

# Input
HEADERS += adapter.h \
           improtocols.h \
           ../irc/irc.h
SOURCES += main.cpp \
           adapter.cpp \
           ../irc/irc.cpp\
           service.cpp

