######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 30 15:20:50 2010
######################################################################

TEMPLATE = app
TARGET = exam1
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += exam1.h
SOURCES += main.cpp
