######################################################################
# Automatically generated by qmake (2.01a) Wed May 27 16:10:38 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network
# Input
HEADERS += printer.h
SOURCES += main.cpp
