######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 11 15:42:28 2012
######################################################################

TEMPLATE = lib
CONFIG += plugin
TARGET = 
DESTDIR = ../protocolplugins
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ircplugin.h
SOURCES += ircplugin.cpp
