######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 30 15:20:50 2010
######################################################################

TEMPLATE = app
TARGET = exam3
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += exam3.h
SOURCES += main.cpp
