######################################################################
# Automatically generated by qmake (2.01a) Fri Sep 9 17:28:32 2011
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += servertests.cpp
